services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - backend_default
  app:
    build:
      context: backend/
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - backend_default

networks:
  backend_default:
    external: true